services : 
  module-app :
    container_name : module-app
    image :  module-app:v1
    build : 
      context : .
    ports :  
      - "402"
    networks : 
      module-web:

  balanceador :
    container_name : balanceador
    image :  balanceador:v1
    build : 
      context : ./balanceador
    ports :  
      - "403:80"
    networks : 
      module-web:
    
networks :
  module-web: